// Every Victorian council's customer-service contact, which takes road hazard reports.
// Source: Vic Councils (Municipal Association of Victoria) council contacts list, October 2026.
// [name, phone, email, website]. An empty email means the council only takes reports through its website.
window.VIC_COUNCILS=[
["Alpine Shire Council","(03) 5755 0555","info@alpineshire.vic.gov.au","www.alpineshire.vic.gov.au"],
["Ararat Rural City Council","(03) 5355 0200","council@ararat.vic.gov.au","www.ararat.vic.gov.au"],
["Ballarat City Council","(03) 5320 5500","ballcity@ballarat.vic.gov.au","www.ballarat.vic.gov.au"],
["Banyule City Council","(03) 9490 4222","enquiries@banyule.vic.gov.au","www.banyule.vic.gov.au"],
["Bass Coast Shire Council","(03) 5671 2211","basscoast@basscoast.vic.gov.au","www.basscoast.vic.gov.au"],
["Baw Baw Shire Council","(03) 5624 2411","bawbaw@bawbawshire.vic.gov.au","www.bawbawshire.vic.gov.au"],
["Bayside City Council","(03) 9599 4444","enquiries@bayside.vic.gov.au","www.bayside.vic.gov.au"],
["Benalla Rural City Council","(03) 5760 2600","council@benalla.vic.gov.au","www.benalla.vic.gov.au"],
["Boroondara City Council","(03) 9278 4444","boroondara@boroondara.vic.gov.au","www.boroondara.vic.gov.au"],
["Brimbank City Council","(03) 9249 4000","info@brimbank.vic.gov.au","www.brimbank.vic.gov.au"],
["Buloke Shire Council","(03) 5478 0100","buloke@buloke.vic.gov.au","www.buloke.vic.gov.au"],
["Campaspe Shire Council","(03) 5481 2200","shire@campaspe.vic.gov.au","www.campaspe.vic.gov.au"],
["Cardinia Shire Council","1300 787 624","mail@cardinia.vic.gov.au","www.cardinia.vic.gov.au"],
["Casey City Council","(03) 9705 5200","caseycc@casey.vic.gov.au","www.casey.vic.gov.au"],
["Central Goldfields Shire Council","(03) 5461 0610","mail@cgoldshire.vic.gov.au","www.centralgoldfields.vic.gov.au"],
["Colac Otway Shire Council","(03) 5232 9400","inq@colacotway.vic.gov.au","www.colacotway.vic.gov.au"],
["Corangamite Shire Council","(03) 5593 7100","shire@corangamite.vic.gov.au","www.corangamite.vic.gov.au"],
["Darebin City Council","(03) 8470 8888","mailbox@darebin.vic.gov.au","www.darebin.vic.gov.au"],
["East Gippsland Shire Council","(03) 5153 9500","feedback@egipps.vic.gov.au","www.eastgippsland.vic.gov.au"],
["Frankston City Council","1300 322 322","info@frankston.vic.gov.au","www.frankston.vic.gov.au"],
["Gannawarra Shire Council","(03) 5450 9333","council@gannawarra.vic.gov.au","www.gannawarra.vic.gov.au"],
["Glen Eira City Council","(03) 9524 3333","mail@gleneira.vic.gov.au","www.gleneira.vic.gov.au"],
["Glenelg Shire Council","(03) 5522 2200","enquiry@glenelg.vic.gov.au","www.glenelg.vic.gov.au"],
["Golden Plains Shire Council","(03) 5220 7111","enquiries@gplains.vic.gov.au","www.goldenplains.vic.gov.au"],
["Greater Bendigo City Council","(03) 5434 6000","requests@bendigo.vic.gov.au","www.bendigo.vic.gov.au"],
["Greater Dandenong City Council","(03) 8571 1000","council@cgd.vic.gov.au","www.greaterdandenong.vic.gov.au"],
["Greater Geelong City Council","(03) 5272 5272","contactus@geelongcity.vic.gov.au","www.geelongcity.vic.gov.au"],
["Greater Shepparton City Council","(03) 5832 9700","council@shepparton.vic.gov.au","greatershepparton.com.au"],
["Hepburn Shire Council","(03) 5348 2306","shire@hepburn.vic.gov.au","www.hepburn.vic.gov.au"],
["Hindmarsh Shire Council","(03) 5391 4444","info@hindmarsh.vic.gov.au","www.hindmarsh.vic.gov.au"],
["Hobsons Bay City Council","1300 179 944","customerservice@hobsonsbay.vic.gov.au","www.hobsonsbay.vic.gov.au"],
["Horsham Rural City Council","(03) 5382 9777","council@hrcc.vic.gov.au","www.hrcc.vic.gov.au"],
["Hume City Council","(03) 9205 2200","email@hume.vic.gov.au","www.hume.vic.gov.au"],
["Indigo Shire Council","(03) 5728 8000","indigoshire@indigoshire.vic.gov.au","www.indigoshire.vic.gov.au"],
["Kingston City Council","1300 653 356","info@kingston.vic.gov.au","www.kingston.vic.gov.au"],
["Knox City Council","(03) 9298 8000","knoxcc@knox.vic.gov.au","www.knox.vic.gov.au"],
["Latrobe City Council","1300 367 700","latrobe@latrobe.vic.gov.au","www.latrobe.vic.gov.au"],
["Loddon Shire Council","(03) 5494 1200","loddon@loddon.vic.gov.au","www.loddon.vic.gov.au"],
["Macedon Ranges Shire Council","(03) 5422 0333","mrsc@mrsc.vic.gov.au","www.mrsc.vic.gov.au"],
["Manningham City Council","(03) 9840 9333","manningham@manningham.vic.gov.au","www.manningham.vic.gov.au"],
["Mansfield Shire Council","(03) 5775 8555","council@mansfield.vic.gov.au","www.mansfield.vic.gov.au"],
["Maribyrnong City Council","(03) 9688 0200","email@maribyrnong.vic.gov.au","www.maribyrnong.vic.gov.au"],
["Maroondah City Council","1300 882 233","maroondah@maroondah.vic.gov.au","www.maroondah.vic.gov.au"],
["Melbourne City Council","(03) 9658 9658","","www.melbourne.vic.gov.au/contactus"],
["Melton City Council","(03) 9747 7200","csu@melton.vic.gov.au","www.melton.vic.gov.au"],
["Merri-bek City Council","(03) 9240 1111","info@merri-bek.vic.gov.au","www.merri-bek.vic.gov.au"],
["Mildura Rural City Council","(03) 5018 8100","mrcc@mildura.vic.gov.au","www.mildura.vic.gov.au"],
["Mitchell Shire Council","(03) 5734 6200","mitchell@mitchellshire.vic.gov.au","www.mitchellshire.vic.gov.au"],
["Moira Shire Council","(03) 5871 9222","info@moira.vic.gov.au","www.moira.vic.gov.au"],
["Monash City Council","(03) 9518 3555","mail@monash.vic.gov.au","www.monash.vic.gov.au"],
["Moonee Valley City Council","(03) 9243 8888","council@mvcc.vic.gov.au","mvcc.vic.gov.au"],
["Moorabool Shire Council","(03) 5366 7100","info@moorabool.vic.gov.au","www.moorabool.vic.gov.au"],
["Mornington Peninsula Shire Council","1300 850 600","customerservice@mornpen.vic.gov.au","www.mornpen.vic.gov.au"],
["Mount Alexander Shire Council","(03) 5471 1700","info@mountalexander.vic.gov.au","www.mountalexander.vic.gov.au"],
["Moyne Shire Council","(03) 5568 0555","moyne@moyne.vic.gov.au","www.moyne.vic.gov.au"],
["Murrindindi Shire Council","(03) 5772 0333","msc@murrindindi.vic.gov.au","www.murrindindi.vic.gov.au"],
["Nillumbik Shire Council","(03) 9433 3111","nillumbik@nillumbik.vic.gov.au","www.nillumbik.vic.gov.au"],
["Northern Grampians Shire Council","(03) 5358 8700","ngshire@ngshire.vic.gov.au","www.ngshire.vic.gov.au"],
["Port Phillip City Council","(03) 9209 6777","","www.portphillip.vic.gov.au"],
["Pyrenees Shire Council","(03) 5349 1100","pyrenees@pyrenees.vic.gov.au","www.pyrenees.vic.gov.au"],
["Queenscliffe Borough Council","(03) 5258 1377","info@queenscliffe.vic.gov.au","www.queenscliffe.vic.gov.au"],
["South Gippsland Shire Council","(03) 5662 9200","council@southgippsland.vic.gov.au","www.southgippsland.vic.gov.au"],
["Southern Grampians Shire Council","(03) 5573 0444","council@sthgrampians.vic.gov.au","www.sthgrampians.vic.gov.au"],
["Stonnington City Council","(03) 8290 1333","council@stonnington.vic.gov.au","www.stonnington.vic.gov.au"],
["Strathbogie Shire Council","(03) 5795 0000","info@strathbogie.vic.gov.au","www.strathbogie.vic.gov.au"],
["Surf Coast Shire Council","(03) 5261 0600","info@surfcoast.vic.gov.au","www.surfcoast.vic.gov.au"],
["Swan Hill Rural City Council","(03) 5036 2333","council@swanhill.vic.gov.au","www.swanhill.vic.gov.au"],
["Towong Shire Council","(02) 6071 5100","info@towong.vic.gov.au","www.towong.vic.gov.au"],
["Wangaratta Rural City Council","(03) 5722 0888","council@wangaratta.vic.gov.au","www.wangaratta.vic.gov.au"],
["Warrnambool City Council","(03) 5559 4800","wbool_city@warrnambool.vic.gov.au","www.warrnambool.vic.gov.au"],
["Wellington Shire Council","1300 366 244","enquiries@wellington.vic.gov.au","www.wellington.vic.gov.au"],
["West Wimmera Shire Council","(03) 5585 9900","council@westwimmera.vic.gov.au","www.westwimmera.vic.gov.au"],
["Whitehorse City Council","(03) 9262 6333","customer.service@whitehorse.vic.gov.au","www.whitehorse.vic.gov.au"],
["Whittlesea City Council","(03) 9217 2170","info@whittlesea.vic.gov.au","www.whittlesea.vic.gov.au"],
["Wodonga City Council","(02) 6022 9300","info@wodonga.vic.gov.au","www.wodonga.vic.gov.au"],
["Wyndham City Council","(03) 9742 0777","mail@wyndham.vic.gov.au","www.wyndham.vic.gov.au"],
["Yarra City Council","(03) 9205 5555","info@yarracity.vic.gov.au","www.yarracity.vic.gov.au"],
["Yarra Ranges Shire Council","1300 368 333","mail@yarraranges.vic.gov.au","www.yarraranges.vic.gov.au"],
["Yarriambiack Shire Council","(03) 5398 0100","info@yarriambiack.vic.gov.au","www.yarriambiack.vic.gov.au"]
];
